name: Scrape Data, build and upload Model

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11' # install the python version needed
          cache: 'pip'
          
      - name: install python packages
        run: pip install -r requirements.txt

      - name: scrape imdb data, upload data to mongodb and build model
        working-directory: model
        run: python app.py -u "${{secrets.MONGODB_URI}}"

      - name: upload model
        working-directory: model
        run: python save.py -c "${{secrets.AZURE_STORAGE_CONNECTION_STRING}}"
